server:
  port: 7070
spring:
  application:
    name: workout-notes
  data:
    mongodb:
      database: workout-notes
      auto-index-creation: true
  webflux:
    multipart:
      maxDiskUsagePerPart: 1024KB
      maxInMemorySize: 1024KB
